# 📘 Practical 9 – Task 1  
## Creating and Manipulating Arrays with NumPy  

---

## 🔹 Introduction
NumPy is a powerful Python library for numerical computing. It provides the `ndarray` object, which allows efficient storage and manipulation of large datasets.  

In this section, you will learn how to:  
- Create **1D, 2D, and 3D arrays**.  
- Perform **reshaping, slicing, and indexing** operations.  
- Explore examples and practice with your own code.  

---

## 🔹 Importing NumPy

In [1]:
import numpy as np

If this command doesn't work, then try this command and then rerun the above command to import numpy

In [ ]:
!pip install numpy # Run this only once if numpy is not installed, else ignore

---

## 🔹 Creating Arrays

### 1D Array


In [2]:
arr1d = np.array([1, 2, 3, 4, 5])  
print("1D Array:", arr1d)

1D Array: [1 2 3 4 5]


### 2D Array


In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])  
print("2D Array:\n", arr2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [ ]:
print(arr2d[:,:2])

[[1 2]
 [4 5]]


In [36]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
print(arr[:,:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### 3D Array

In [37]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  
print("3D Array:\n", arr3d)

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


---

## 🔹 Reshaping Arrays
Reshaping changes the dimensions of an array without changing its data.

In [5]:
arr = np.arange(1, 7)   # [1 2 3 4 5 6]  
reshaped = arr.reshape(2, 3)  
print("Original 1D:", arr)  
print("Reshaped to 2D:\n", reshaped)

Original 1D: [1 2 3 4 5 6]
Reshaped to 2D:
 [[1 2 3]
 [4 5 6]]


---

## 🔹 Slicing Arrays
Slicing extracts parts of an array.

In [6]:
print("First row of 2D array:", arr2d[0])     # [1 2 3]  
print("First two elements of 1D array:", arr1d[:2])  # [1 2]  
print("Submatrix from 2D array:\n", arr2d[:, 1:])    # [[2 3], [5 6]]

First row of 2D array: [1 2 3]
First two elements of 1D array: [1 2]
Submatrix from 2D array:
 [[2 3]
 [5 6]]


---

## 🔹 Indexing Arrays
Indexing retrieves specific elements.

In [38]:
print("Element at [1,0,1] in 3D array:", arr3d[1, 0, 1])  # 6  
print("Element at [0,2] in 2D array:", arr2d[0, 2])       # 3

Element at [1,0,1] in 3D array: 6
Element at [0,2] in 2D array: 3


---

## 🔹 Try It Yourself 💡
👉 Modify the code below to experiment:  
- Create a new array with different numbers.  
- Reshape it into different dimensions.  
- Slice and index to extract interesting parts.

# Your practice space

In [39]:
my_array = np.arange(10)   # Try changing this  
print("My Array:", my_array)

reshaped = my_array.reshape(2, 5)   # Try reshaping differently  
print("Reshaped:\n", reshaped)

print("Slice:", my_array[2:7])      # Try different slices  
print("Index:", reshaped[1, 3])     # Try different indices

My Array: [0 1 2 3 4 5 6 7 8 9]
Reshaped:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Slice: [2 3 4 5 6]
Index: 8


---

## 🔹 Practice Problems

### Problem 1
Create a 1D array of numbers from 1 to 3*n. n is a variable 

Reshape it into a 3×n matrix.  

Extract the last column.  

In [45]:
# Write your code here
n = 6
arr = np.arange(1, (3*n)+1)
arrmod = arr.reshape((3,n))
print(arrmod)
print(arrmod[:,-1])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[ 6 12 18]


---

### Problem 2
Create a 2D array:

```python
[[10, 20, 30],  
 [40, 50, 60],  
 [70, 80, 90]] 
 ``` 

Slice out the middle column.

In [47]:
# Write your code here
# Answer [20, 50, 80]
arr2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr2)
print(arr2[:,1])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[20 50 80]


---

### Problem 3
Create a 3D array with shape (2,2,3):  
```python
[[[1,2,3],
  [4,5,6]],  
 [[7,8,9],
  [10,11,12]]]
 ```  

Index the element `11`. 

In [50]:
# Write your code here
arr3 = np.array([[[1,2,3],[4,5,6]],  [[7,8,9],[10,11,12]]])
print(arr3[1,1,1])

11


---

### Problem 4
Create a 1D array of even numbers from 2 to 20.  
Reshape it into a 2×5 matrix.  
Slice out the first row. 

In [52]:
# Write your code here
arr4 = np.arange(2,21,2)
print(arr4)
print(arr4.reshape((2,5)))

[ 2  4  6  8 10 12 14 16 18 20]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
