# 📘 Practical 9 – Task 2  
## Array Mathematics with NumPy  

---

## 🔹 Introduction
NumPy makes mathematical operations on arrays simple and efficient.  
Instead of looping through elements manually, NumPy allows **vectorized operations** that are faster and more concise.  

In this section, you will learn how to:  
- Perform **element‑wise addition, subtraction, multiplication, and division**.  
- Calculate the **dot product** of two vectors.  
- Calculate the **cross product** of two vectors.  

---

## 🔹 Creating Arrays
Let’s start by creating two arrays of the same shape.

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3])  
arr2 = np.array([4, 5, 6])  

print("Array 1:", arr1)  
print("Array 2:", arr2)

Array 1: [1 2 3]
Array 2: [4 5 6]


---

## 🔹 Element‑wise Operations
NumPy applies operations element by element when arrays have the same shape.

In [3]:
print("Addition:", arr1 + arr2)  
print("Subtraction:", arr1 - arr2)  
print("Multiplication:", arr1 * arr2)  
print("Division:", arr1 / arr2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


---

## 🔹 Dot Product
The dot product multiplies corresponding elements and sums them.

In [5]:
print(arr1)
print(arr2)
dot_product = np.dot(arr1, arr2)  
print("Dot Product:", dot_product)

[1 2 3]
[4 5 6]
Dot Product: 32



---

## 🔹 Cross Product
The cross product applies only to 3‑dimensional vectors.

In [6]:
cross_product = np.cross(arr1, arr2)  
print("Cross Product:", cross_product)

Cross Product: [-3  6 -3]


---

## 🔹 Try It Yourself 💡
👉 Experiment with your own arrays:  
- Create two arrays of length 4 or 5.  
- Perform element‑wise operations.  
- Try dot and cross products (cross product only works for 3D vectors).  

# Your practice space


In [ ]:
a = np.array([2, 4, 6])  
b = np.array([1, 3, 5])  

print("Addition:", a + b)  
print("Dot Product:", np.dot(a, b))  
print("Cross Product:", np.cross(a, b))

---

## 🔹 Practice Problems

### Problem 1
Create two arrays:  
```python
arr1 = [10, 20, 30]  
arr2 = [1, 2, 3]
```  
Perform element‑wise multiplication.  


In [7]:
# Write your code here
arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3])
print(arr1 * arr2)

[10 40 90]


---

### Problem 2
Create two arrays:  
```python
arr1 = [2, 4, 6]  
arr2 = [1, 3, 5]  
```
Find the dot product. 

In [8]:
# Write your code here
arr1 = [2, 4, 6]  
arr2 = [1, 3, 5] 
print(np.dot(arr1,arr2))

44


---

### Problem 3
Create two vectors:  
```python
v1 = [1, 0, 0]  
v2 = [0, 1, 0]  
```
Find the cross product. 

In [9]:
# Write your code here
arr1 = np.array([1,0,0])
arr2 = np.array([0,1,0])
print(np.cross(arr1,arr2))

[0 0 1]


---

### Problem 4
Create two arrays of length 4:  
```python
arr1 = [5, 10, 15, 20]  
arr2 = [2, 4, 6, 8]  
```
Perform element‑wise division.

In [11]:
# Write your code here
arr1 = np.array([5, 10, 15, 20])
arr2 = np.array([2, 4, 6, 8])
print(arr1/arr2)

[2.5 2.5 2.5 2.5]
